version: '3'

networks:
  dev:

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./nginx/certs:/etc/letsencrypt
  #     - ./nginx/html:/usr/share/nginx/html
  #   command: >
  #     certonly --webroot
  #     -w /usr/share/nginx/html
  #     -d techg.online
  #     -d www.techg.online
  #     --email metodievi038@gmail.com
  #     --agree-tos
  #     --no-eff-email

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
    networks:
      - dev
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      NODE_ENV: production
    depends_on:
      - postgres
    volumes:
      - ./server/static:/app/static
      
  frontend:
    build:
      context: ./client/techg
    expose:
      - "3000"
    networks:
      - dev
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://techg.online/api

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - dev

volumes:
  postgres_data: