import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import StoreProvider from "./store/StoreProvider";

export const metadata = {
  title: "TechG | Shop with pleasure",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link href="https://db.onlinewebfonts.com/c/381560810e4c36d16a07abb03254e264?family=JejuGothic" rel="stylesheet">
        </link>
        <meta name="viewport" content="width=width-device, initial-scale=1.0" />
      </head>
      <body className="pt-50">
        <StoreProvider>
          <Navbar />
            {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
