import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import StoreProvider from "./store/StoreProvider";
import Loader from "./components/loader";

export const metadata = {
  title: "TechG | Shop with pleasure",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link href="https://db.onlinewebfonts.com/c/381560810e4c36d16a07abb03254e264?family=JejuGothic" rel="stylesheet">
        </link>
        <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="viewport" content="width=width-device, initial-scale=1.0" />
        <meta name="google-site-verification" content="INZ2RtaCfSptWZa1xt8noTLTrZydPsed4rnqJE1Msyw" />
      </head>
      <body className="pt-35 md:pt-50">
        <StoreProvider>
          <Loader />
          <Navbar />
            {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
